### ISSUE TITLE
How does this plugin compares to other options

### ISSUE THREAD

**Issue by lorenzo** [cakemanager/cakephp-posttypes#1]
Hey, just a friendly question. Before you spend time creating and improving this library, are there any advantages planned for it when compared to, for example, the CRUD pluging?

https://github.com/FriendsOfCake/crud/tree/cake3

I think you could instead reuse the functionality in that other plugin to improve the cakemanager project.

**Comment by bobmulder** [comment]
Hey lorenzo,

Thanks for your message. I've worked with the CRUD-plugin before, and it works great.

The CakeManager-project allows an user to have an automatic working admin-area. The PostTypes-project allows users to register posttypes. The projects are mainly for personal use, and maybe it could be useful in future for other programmers.

When you use the CRUD-plugin, you have to create a controller and views on your own. Via the PostTypes-plugin you are able to register a type, without generating controllers and views, and it's working for your admin-panel. So, it works easier and faster.
Note that this is a solution for your admin-area. Not for your front-end.

I think it's another approach of the 'problem' ;)

I want to build automatic api's, and I am planning to use the CRUD plugin for that.

What's your view about this? I saw you worked on Cake 3, and contributed to the CRUD-plugin?

Thanks!

Bob

**Comment by lorenzo** [comment]
I use CRUD very heavily in most of my apps. While it is true that you need a Controller, it is not 100% true that  you need views. This project is an attempt to have completely dynamic views https://github.com/friendsofcake/crud-view

I guess that with a bit of extra work you could remove the need for having a controller at all, for example with the use of a specialized DispatcherFilter.

My idea is, if you think the Crud plugin can be extended or improved to help you with the creation of this plugin, just dump your ideas as a RFC ticket or a pull request!

**Comment by bobmulder** [comment]
Didn't see that dynamic views are possible! Great!

The PostTypes-plugin won't be a large plugin. I will keep it for the CakeManager. In future I will think about extending the functionality of the CRUD-plugin! That would be great :)
